# Generated by Django 2.2.5 on 2019-09-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='enviroment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='sensor.Enviroment'),
        ),
    ]
