# Generated by Django 2.2.5 on 2019-09-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_enviroment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Placa',
                'verbose_name_plural': 'Placas',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDate', models.CharField(max_length=10, verbose_name='Nome')),
                ('unity', models.CharField(max_length=10, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AddField(
            model_name='enviroment',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.Board')),
                ('type_sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.Type')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.Sensor')),
            ],
            options={
                'verbose_name': 'Dado do Sensor',
                'verbose_name_plural': 'Dados do Sensor',
            },
        ),
    ]
