# Generated by Django 2.2.5 on 2019-09-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20190911_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='enviroment',
            new_name='envorinment',
        ),
    ]
