# Generated by Django 2.2.5 on 2019-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20190905_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(max_length=100, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='type',
            name='typeDate',
            field=models.CharField(max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unity',
            field=models.CharField(max_length=10, verbose_name='Unidade'),
        ),
    ]
