# Generated by Django 2.2.5 on 2019-09-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20190905_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='sensor.Sensor'),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição'),
        ),
    ]
