# Generated by Django 2.2.5 on 2019-09-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20190911_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enviroment',
            new_name='Environment',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='envorinment',
            new_name='environment',
        ),
    ]
