# Generated by Django 2.2.5 on 2019-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_auto_20190905_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='type_sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='typeDate',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unity',
            field=models.CharField(blank=True, max_length=10, verbose_name='Unidade'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
