# Generated by Django 2.2.5 on 2019-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_auto_20190909_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='typeDate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo'),
        ),
    ]
